### ISSUE TITLE
class heritage OsdWindow.OsdWindowConstraint is not an object or null

### ISSUE THREAD

**Issue by guidoenr** [zhrexl/DrawOnYourScreen2#10] opened 2022-08-29 17:11 UTC
Hey guys, trying to install this extension in Kali Linux. 

When i'm trying to enable the extension from the **Extensions** section, i get the following error message:
```bash
class heritage OsdWindow.OsdWindowConstraint is not an object or null
```
 I tried both methods of instalation:
 - Manually
 - in gnome extensions
 
 Both didn't work to me

![image](https://user-images.githubusercontent.com/47611900/187256360-da021552-f835-4a48-8828-78e3174468b3.png)

**Comment by JaldeaR** [comment] 2022-09-19 11:35
Same problem in pop_os 22.04 LTS
Added gnome version 42 to metadata.json when i tried to enable draw-on-your-screen2 after reloading i got the same result.
`class heritage OsdWindow.OsdWindowConstraint is not an object or null`
![Screenshot from 2022-09-19 13-34-56](https://user-images.githubusercontent.com/58230005/191008490-821d8353-d04c-4a71-bfb1-cf44f98b584a.png)

**Comment by zhrexl** [comment] 2022-09-19 11:51
The answer is [Here](https://github.com/zhrexl/DrawOnYourScreen2/issues/6) .
I'll be closing this issue as it is a duplicate of #6.

I'll update the extension on gnome extension soon but for now use the git version.

**Closed by zhrexl** 2022-09-19 11:51 UTC

**Comment by JaldeaR** [comment] 2022-09-19 13:56
Thanks @zhrexl i've updated other comments aswell to redirect towards the gnome42 version.

also added a coment at https://extensions.gnome.org/extension/4937/draw-on-you-screen-2/
